import { PRISMA_NODES } from "./Constants"

export const prisma_data = {
    current_state_nodes: [
        { id: 'initial', label: PRISMA_NODES.INITIAL_SEARCH, x: 20, y: 0, styleType: 'main', clickAble:false },
        { id: 'living', label: PRISMA_NODES.AUTO_UPDATE, x: 240, y: 0, styleType: 'main', clickAble:false },
        { id: 'manual', label: PRISMA_NODES.MANUAL_UPDATE, x: 460, y: 0, styleType: 'secondary', clickAble:true },
        { id: 'total', label: PRISMA_NODES.TOTAL_IDENTIFIED, x: 150, y: 100, styleType: 'main', clickAble:false },
        { id: 'duplicate', label: PRISMA_NODES.DUPLICATES, x: 400, y: 150, styleType: 'main', clickAble:false },
        { id: 'unique', label: PRISMA_NODES.AFTER_DUPLICATES, x: 150, y: 190, styleType: 'main', clickAble:false },
        { id: 'screened', label: PRISMA_NODES.SCREENED, x: 150, y: 290, styleType: 'main' , clickAble:false},
        { id: 'unscreened', label: PRISMA_NODES.CURRENTLY_SCREENING, x: 400, y: 250, styleType: 'main' , clickAble:false},
        { id: 'fulltext_review', label: PRISMA_NODES.FULL_TEXT, x: 150, y: 440, styleType: 'main', clickAble:false },
        { id: 'excluded_by_title', label: PRISMA_NODES.EXCLUDED_TITLE, x: 400, y: 320, styleType: 'main', clickAble:false },
        { id: 'excluded_by_abstract', label: PRISMA_NODES.EXCLUDED_ABSTRACT, x: 400, y: 390, styleType: 'main' , clickAble:false},
        { id: 'excluded_by_fulltext', label: PRISMA_NODES.EXCLUDED_FULL_TEXT, x: 400, y: 540, styleType: 'secondary', clickAble:true },
        { id: 'unscreened_fulltext', label: PRISMA_NODES.CURRENTLY_SCREENING_FULL_TEXT, x: 400, y: 460, styleType: 'main', clickAble:false },
        { id: 'analysis', label: PRISMA_NODES.SYSTEMATIC_REVIEW, x: 150, y: 580, styleType: 'secondary' , clickAble:true},
        { id: 'include', label: PRISMA_NODES.META_ANALYSIS, x: 150, y: 700, styleType: 'secondary' , clickAble:true},
    ],
    current_state_connections: [
        { from: 'initial', to: 'total', type: 'left-right-bottom' },
        { from: 'living', to: 'total', type: 'left-right-bottom' },
        { from: 'manual', to: 'total', type: 'left-right-bottom' },
        { from: 'total', to: 'duplicate', type: 'left-to-center-right' },
        { from: 'total', to: 'unique', type: 'straight' },
        { from: 'unique', to: 'screened', type: 'straight' },
        { from: 'unique', to: 'unscreened', type: 'left-to-center-right' },
        { from: 'screened', to: 'fulltext_review', type: 'straight' },
        { from: 'screened', to: 'excluded_by_title', type: '2-left-to-center-right' },
        { from: 'screened', to: 'excluded_by_abstract', type: '2-left-to-center-right' },
        { from: 'fulltext_review', to: 'excluded_by_fulltext', type: '2-left-to-center-right' },
        { from: 'fulltext_review', to: 'analysis', type: 'straight' },
        { from: 'fulltext_review', to: 'unscreened_fulltext', type: '2-left-to-center-right' },
        { from: 'analysis', to: 'include', type: 'straight' },
    ],
    initial_state_nodes: [
        { id: 'initial', label: PRISMA_NODES.INITIAL_SEARCH, x: 150, y: 0, styleType: 'main', clickAble:false },
        { id: 'duplicate', label: PRISMA_NODES.DUPLICATES, x: 400, y: 70, styleType: 'main', clickAble:false },
        { id: 'unique', label: PRISMA_NODES.AFTER_DUPLICATES, x: 150, y: 130, styleType: 'main' , clickAble:false},
        { id: 'screened', label: PRISMA_NODES.SCREENED, x: 150, y: 250, styleType: 'main' , clickAble:false},
        { id: 'fulltext_review', label: PRISMA_NODES.FULL_TEXT, x: 150, y: 420, styleType: 'main', clickAble:false },
        { id: 'excluded_by_title', label: PRISMA_NODES.EXCLUDED_TITLE, x: 400, y: 290, styleType: 'main' , clickAble:false},
        { id: 'excluded_by_abstract', label: PRISMA_NODES.EXCLUDED_ABSTRACT, x: 400, y: 370, styleType: 'main', clickAble:false },
        { id: 'excluded_by_fulltext', label: PRISMA_NODES.EXCLUDED_FULL_TEXT, x: 400, y: 470, styleType: 'secondary' , clickAble:true},
        { id: 'analysis', label: PRISMA_NODES.SYSTEMATIC_REVIEW, x: 150, y: 520, styleType: 'secondary', clickAble:true },
        { id: 'include', label: PRISMA_NODES.META_ANALYSIS, x: 150, y: 630, styleType: 'secondary', clickAble:true },
    ],
    initial_state_connections: [
        { from: 'initial', to: 'unique', type: 'straight' },
        { from: 'initial', to: 'duplicate', type: 'left-to-center-right' },
        { from: 'unique', to: 'screened', type: 'straight' },
        { from: 'screened', to: 'fulltext_review', type: 'straight' },
        { from: 'screened', to: 'excluded_by_title', type: '2-left-to-center-right' },
        { from: 'screened', to: 'excluded_by_abstract', type: '2-left-to-center-right' },
        { from: 'fulltext_review', to: 'excluded_by_fulltext', type: 'left-to-center-right' },
        { from: 'fulltext_review', to: 'analysis', type: 'straight' },
        { from: 'analysis', to: 'include', type: 'straight' },
    ],
    living_state_nodes: [
        { id: 'living', label: PRISMA_NODES.AUTO_UPDATE, x: 0, y: 0, styleType: 'main', clickAble:false },
        { id: 'duplicate', label: PRISMA_NODES.DUPLICATES, x: 240, y: 70, styleType: 'main', clickAble:false },
        { id: 'unique', label: PRISMA_NODES.AFTER_DUPLICATES, x: 0, y: 130, styleType: 'main' , clickAble:false},
        { id: 'screened', label: PRISMA_NODES.SCREENED, x: 0, y: 250, styleType: 'main', clickAble:false },
        { id: 'fulltext_review', label: PRISMA_NODES.FULL_TEXT, x: 0, y: 420, styleType: 'main', clickAble:false },
        { id: 'excluded_by_title', label: PRISMA_NODES.EXCLUDED_TITLE, x: 240, y: 290, styleType: 'main', clickAble:false },
        { id: 'excluded_by_abstract', label: PRISMA_NODES.EXCLUDED_ABSTRACT, x: 240, y: 370, styleType: 'main', clickAble:false },
        { id: 'excluded_by_fulltext', label: PRISMA_NODES.EXCLUDED_FULL_TEXT, x: 240, y: 470, styleType: 'secondary' , clickAble:true},
        { id: 'analysis', label: PRISMA_NODES.SYSTEMATIC_REVIEW, x: 0, y: 520, styleType: 'secondary', clickAble:true },
        { id: 'include', label: PRISMA_NODES.META_ANALYSIS, x: 0, y: 630, styleType: 'secondary' , clickAble:true},
    ],
    living_state_connections: [
        { from: 'living', to: 'unique', type: 'straight' },
        { from: 'living', to: 'duplicate', type: 'left-to-center-right' },
        { from: 'unique', to: 'screened', type: 'straight' },
        { from: 'screened', to: 'fulltext_review', type: 'straight' },
        { from: 'screened', to: 'excluded_by_title', type: '2-left-to-center-right' },
        { from: 'screened', to: 'excluded_by_abstract', type: '2-left-to-center-right' },
        { from: 'fulltext_review', to: 'excluded_by_fulltext', type: 'left-to-center-right' },
        { from: 'fulltext_review', to: 'analysis', type: 'straight' },
        { from: 'analysis', to: 'include', type: 'straight' },
    ]

}