import { PRISMA_NODES } from "./Constants"

export const prisma_data = {
    current_state_nodes: [
        { id: 'initial', label: PRISMA_NODES.INITIAL_SEARCH, x: 20, y: 0, styleType: 'main' },
        { id: 'automate', label: PRISMA_NODES.AUTO_UPDATE, x: 240, y: 0, styleType: 'main' },
        { id: 'manual', label: PRISMA_NODES.MANUAL_UPDATE, x: 460, y: 0, styleType: 'secondary' },
        { id: 'total', label: PRISMA_NODES.TOTAL_IDENTIFIED, x: 150, y: 100, styleType: 'main' },
        { id: 'duplicates', label: PRISMA_NODES.DUPLICATES, x: 400, y: 150, styleType: 'main' },
        { id: 'after_duplicates', label: PRISMA_NODES.AFTER_DUPLICATES, x: 150, y: 190, styleType: 'main' },
        { id: 'screened', label: PRISMA_NODES.SCREENED, x: 150, y: 290, styleType: 'main' },
        { id: 'currently_screening', label: PRISMA_NODES.CURRENTLY_SCREENING, x: 400, y: 250, styleType: 'main' },
        { id: 'full_text', label: PRISMA_NODES.FULL_TEXT, x: 150, y: 440, styleType: 'main' },
        { id: 'excluded_title', label: PRISMA_NODES.EXCLUDED_TITLE, x: 400, y: 320, styleType: 'main' },
        { id: 'excluded_abstract', label: PRISMA_NODES.EXCLUDED_ABSTRACT, x: 400, y: 390, styleType: 'main' },
        { id: 'excluded_full_text', label: PRISMA_NODES.EXCLUDED_FULL_TEXT, x: 400, y: 540, styleType: 'secondary' },
        { id: 'currently_screening_full_text', label: PRISMA_NODES.CURRENTLY_SCREENING_FULL_TEXT, x: 400, y: 460, styleType: 'main' },
        { id: 'systematic_review', label: PRISMA_NODES.SYSTEMATIC_REVIEW, x: 150, y: 580, styleType: 'secondary' }
    ],
    current_state_connections: [
        { from: 'initial', to: 'total', type: 'left-right-bottom' },
        { from: 'automate', to: 'total', type: 'left-right-bottom' },
        { from: 'manual', to: 'total', type: 'left-right-bottom' },
        { from: 'total', to: 'duplicates', type: 'left-to-center-right' },
        { from: 'total', to: 'after_duplicates', type: 'straight' },
        { from: 'after_duplicates', to: 'screened', type: 'straight' },
        { from: 'after_duplicates', to: 'currently_screening', type: 'left-to-center-right' },
        { from: 'screened', to: 'full_text', type: 'straight' },
        { from: 'screened', to: 'excluded_title', type: '2-left-to-center-right' },
        { from: 'screened', to: 'excluded_abstract', type: '2-left-to-center-right' },
        { from: 'full_text', to: 'excluded_full_text', type: '2-left-to-center-right' },
        { from: 'full_text', to: 'systematic_review', type: 'straight' },
        { from: 'full_text', to: 'currently_screening_full_text', type: '2-left-to-center-right' },
        { from: 'systematic_review', to: 'meta_analysis', type: 'straight' },
    ],
    initial_state_nodes: [
        { id: 'initial', label: PRISMA_NODES.INITIAL_SEARCH, x: 150, y: 0, styleType: 'main' },
        { id: 'duplicates', label: PRISMA_NODES.DUPLICATES, x: 400, y: 70, styleType: 'main' },
        { id: 'after_duplicates', label: PRISMA_NODES.AFTER_DUPLICATES, x: 150, y: 130, styleType: 'main' },
        { id: 'screened', label: PRISMA_NODES.SCREENED, x: 150, y: 250, styleType: 'main' },
        { id: 'full_text', label: PRISMA_NODES.FULL_TEXT, x: 150, y: 420, styleType: 'main' },
        { id: 'excluded_title', label: PRISMA_NODES.EXCLUDED_TITLE, x: 400, y: 290, styleType: 'main' },
        { id: 'excluded_abstract', label: PRISMA_NODES.EXCLUDED_ABSTRACT, x: 400, y: 370, styleType: 'main' },
        { id: 'excluded_full_text', label: PRISMA_NODES.EXCLUDED_FULL_TEXT, x: 400, y: 470, styleType: 'secondary' },
        { id: 'systematic_review', label: PRISMA_NODES.SYSTEMATIC_REVIEW, x: 150, y: 520, styleType: 'secondary' },
        { id: 'meta_analysis', label: PRISMA_NODES.META_ANALYSIS, x: 150, y: 630, styleType: 'secondary' },
    ],
    initial_state_connections: [
        { from: 'initial', to: 'after_duplicates', type: 'straight' },
        { from: 'initial', to: 'duplicates', type: 'left-to-center-right' },
        { from: 'after_duplicates', to: 'screened', type: 'straight' },
        { from: 'screened', to: 'full_text', type: 'straight' },
        { from: 'screened', to: 'excluded_title', type: '2-left-to-center-right' },
        { from: 'screened', to: 'excluded_abstract', type: '2-left-to-center-right' },
        { from: 'full_text', to: 'excluded_full_text', type: 'left-to-center-right' },
        { from: 'full_text', to: 'systematic_review', type: 'straight' },
        { from: 'systematic_review', to: 'meta_analysis', type: 'straight' },
    ],
    living_state_nodes: [
        { id: 'living', label: PRISMA_NODES.AUTO_UPDATE, x: 0, y: 0, styleType: 'main' },
        { id: 'duplicates', label: PRISMA_NODES.DUPLICATES, x: 240, y: 70, styleType: 'main' },
        { id: 'after_duplicates', label: PRISMA_NODES.AFTER_DUPLICATES, x: 0, y: 130, styleType: 'main' },
        { id: 'screened', label: PRISMA_NODES.SCREENED, x: 0, y: 250, styleType: 'main' },
        { id: 'full_text', label: PRISMA_NODES.FULL_TEXT, x: 0, y: 420, styleType: 'main' },
        { id: 'excluded_title', label: PRISMA_NODES.EXCLUDED_TITLE, x: 240, y: 290, styleType: 'main' },
        { id: 'excluded_abstract', label: PRISMA_NODES.EXCLUDED_ABSTRACT, x: 240, y: 370, styleType: 'main' },
        { id: 'excluded_full_text', label: PRISMA_NODES.EXCLUDED_FULL_TEXT, x: 240, y: 470, styleType: 'secondary' },
        { id: 'systematic_review', label: PRISMA_NODES.SYSTEMATIC_REVIEW, x: 0, y: 520, styleType: 'secondary' },
        { id: 'meta_analysis', label: PRISMA_NODES.META_ANALYSIS, x: 0, y: 630, styleType: 'secondary' },
    ],
    living_state_connections: [
        { from: 'living', to: 'after_duplicates', type: 'straight' },
        { from: 'living', to: 'duplicates', type: 'left-to-center-right' },
        { from: 'after_duplicates', to: 'screened', type: 'straight' },
        { from: 'screened', to: 'full_text', type: 'straight' },
        { from: 'screened', to: 'excluded_title', type: '2-left-to-center-right' },
        { from: 'screened', to: 'excluded_abstract', type: '2-left-to-center-right' },
        { from: 'full_text', to: 'excluded_full_text', type: 'left-to-center-right' },
        { from: 'full_text', to: 'systematic_review', type: 'straight' },
        { from: 'systematic_review', to: 'meta_analysis', type: 'straight' },
    ]

}